config/routes.rb
Soba::Application.routes.draw do

  root :to => "home#index"

  devise_for :users

  match 'students' => 'students#index'
  
  resources :papers, :path => "/students/papers"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    #  Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end

    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/paper.rb
class Paper < ActiveRecord::Base
  attr_accessible :attachment, :title, :year_written
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for our model
  #   name added
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  # attr_accessible :title, :body

  # Validate presence + uniqueness of "name" attribute
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    @paper = Paper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/new
  # GET /papers/new.json
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(params[:paper])

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render json: @paper, status: :created, location: @paper }
      else
        format.html { render action: "new" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.json
  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to papers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :only_allow_student

  def index
    
  end

  # This method limits access to users with the admin or student role
  def only_allow_student
    redirect_to root_path, :alert => 'Not authorized as a student.' unless current_user.has_any_role? :admin, { :name => :student }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "State of Black Asheville"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
-#
  %div#navContent
    .carousel#myCarousel
      / Carousel items
      .carousel-inner
        .item.active.glossy
          %h1 Headline
          %p  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula eleifend vulputate. Pellentesque blandit faucibus odio, eget scelerisque leo lacinia sit amet. Aliquam id viverra nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis interdum vestibulum tempor. Etiam nulla leo, vulputate nec vestibulum faucibus, semper quis velit. Suspendisse euismod velit non magna molestie id sollicitudin diam dignissim.
        .item.glossy
          %h1 Headline Two
          %p Lorem ipsum dolor sit amet, consectetur apidiscing elit.
      / Carousel nav
      %a.carousel-control.left{"data-slide" => "prev", :href => "#myCarousel"} ‹
      %a.carousel-control.right{"data-slide" => "next", :href => "#myCarousel"} ›



.river
  %ul.thumbnails
    %li
      .thumbnail
        %img{:alt => "", :src => "http://placehold.it/160x120"}
    %h2 Asheville City Schools Annual Report
    %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula eleifend vulputate. Pellentesque blandit faucibus odio, eget scelerisque leo lacinia sit amet. Aliquam id viverra nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra
  %ul.thumbnails
    %li
      .thumbnail
        %img{:alt => "", :src => "http://placehold.it/160x120"}
    %h2 27 Views of Asheville
    %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula eleifend vulputate. Pellentesque blandit faucibus odio, eget scelerisque leo lacinia sit amet. Aliquam id viverra nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra
  %ul.thumbnails
    %li
      .thumbnail
        %img{:alt => "", :src => "http://placehold.it/160x120"}
    %h2 Research Symposium Notes
    %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula eleifend vulputate. Pellentesque blandit faucibus odio, eget scelerisque leo lacinia sit amet. Aliquam id viverra nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra

/  %div.alert.alert-info
/   %a.close{"data-dismiss" => "alert"} &times;
/    %h4.alert-heading Heads up!
/    This website is in active development and certain features of the site may not function as intended.

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    &copy; 2012 - Github - Terms of Service - Privacy Policy - Contact Us - 
    %a{:href => "students"} Student Login

app/views/layouts/_header.html.haml
%header.container{:role => "banner"}
  %div#logo
  %nav#navigationContainer.navigation-menu
    %div#navigation-menu
      %ul.nav.nav-pills
        %li
          = link_to 'Home', '/'
        %li
          = link_to 'Issues', '/'
        %li
          = link_to 'Goals', '/'
        %li
          = link_to 'News & Events', '/'
        %li
          = link_to 'Resources', '/'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag	"application", :media => "all"
    = javascript_include_tag 	"application"
    %meta{:charset => "utf-8"}
    = csrf_meta_tags
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
  %body

    / Header
    = render 'layouts/header'
    %div.container

      / Alerts and Notices
      - if notice
        %div.alert
          = notice
      - if alert
        %div.alert
          = alert

      / Content Area
      %section.span8
        = yield

      / Sidebar
      %section.span4
        = yield :sidebar
        %section#mailingList
          %header.widget-header
            %h4 Join Our Mailing List
          %div.widget-content
            Sup
            %br 
            Sup two
            %br 
            Sup three
            %br 
            Sup four
        %section#mailingList
          %header.widget-header
            %h4 Join Our Mailing List
          %div.widget-content
            Sup
            %br 
            Sup two
            %br 
            Sup three
            %br 
            Sup four
        %section#mailingList
          %header.widget-header
            %h4 Join Our Mailing List
          %div.widget-content
            Sup
            %br 
            Sup two
            %br 
            Sup three
            %br 
            Sup four

    / Footer
    = render 'layouts/footer'

app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br />
    <%= f.text_field :attachment %>
  </div>
  <div class="field">
    <%= f.label :year_written %><br />
    <%= f.date_select :year_written %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<h1>Listing papers</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Attachment</th>
    <th>Year written</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @papers.each do |paper| %>
  <tr>
    <td><%= paper.title %></td>
    <td><%= paper.attachment %></td>
    <td><%= paper.year_written %></td>
    <td><%= link_to 'Show', paper %></td>
    <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
    <td><%= link_to 'Destroy', paper, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paper', new_paper_path %>

app/views/papers/new.html.erb
<h1>New paper</h1>

<%= render 'form' %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @paper.title %>
</p>

<p>
  <b>Attachment:</b>
  <%= @paper.attachment %>
</p>

<p>
  <b>Year written:</b>
  <%= @paper.year_written %>
</p>


<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>

app/views/students/index.html.haml
- provide(:title, 'Student Home')

%h2 Welcome !
%p 
  You can contact the following people for research assistance:
  %ul
    %li <strong>Rachael Burrello</strong>: 336williams@gmail.com or (828) 513-6708
    %li <strong>Grace Salzer</strong>: salzer@live.unc.edu

%h2 Updates
%p 
  %em April 6, 2012 -
  Resources are now working properly.

%p
  %em March 27, 2012 -
  Papers are online and accessible once again. Upload paper functionality is working properly. Resources area will be rolled out within the next day or two.

app/views/users/index.html.erb
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>